apiVersion: apps/v1
kind: Deployment
metadata:
  name: dari-deployment
  labels:
    app: dari-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dari-app-pod
      app: demo-dari-app
  template:
    metadata:
      name: dari-app-pod
      labels:
        name: dari-app-pod
        app: demo-dari-app

    spec:
      containers:
      - name: dari
        image: amineturki/darifront:v2
        ports:
        - containerPort: 80
